# Generated by Django 5.1.4 on 2025-01-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepair',
            name='president',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidatepair',
            name='vice_president',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='candidatepair',
            name='president_photo',
            field=models.FileField(null=True, upload_to='candidates/'),
        ),
        migrations.AddField(
            model_name='candidatepair',
            name='vice_president_photo',
            field=models.FileField(null=True, upload_to='candidates/'),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
