# Generated by Django 5.1.5 on 2025-01-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_authtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatepair',
            name='president_photo',
        ),
        migrations.RemoveField(
            model_name='candidatepair',
            name='vice_president_photo',
        ),
        migrations.AddField(
            model_name='candidatepair',
            name='candidate_pair_photo',
            field=models.FileField(blank=True, null=True, upload_to='candidates/'),
        ),
    ]
