# Generated by Django 5.1.5 on 2025-03-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_candidatepair_president_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepair',
            name='candidate_pair_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
