# Generated by Django 5.1.5 on 2025-03-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_candidatepair_candidate_pair_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepair',
            name='isEmptyBox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidatepair',
            name='document_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatepair',
            name='mission',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='candidatepair',
            name='president',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidatepair',
            name='programs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='candidatepair',
            name='social_media',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatepair',
            name='vice_president',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidatepair',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
