# Generated by Django 5.1.5 on 2025-03-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_candidatepair_isemptybox_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatepair',
            old_name='isEmptyBox',
            new_name='is_empty_box',
        ),
    ]
