# Generated by Django 5.1.5 on 2025-03-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_isemptybox_candidatepair_is_empty_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepair',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
